### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by bastianlb** [meteotest/h5pySWMR#1]
I'm interested in using your library, but am getting an error while running tests on `debian`. Can you provide any insight?

Tried this on redis 3.0.0 and 2.8

```
~/h2oserver$ dpkg -l | grep "hdf5"
ii  hdf5-helpers                   1.8.13+docs-15              amd64        Hierarchical Data Format 5 (HDF5) - Helper tools
ii  hdf5-tools                     1.8.13+docs-15              amd64        Hierarchical Data Format 5 (HDF5) - Runtime tools
rc  libhdf5-7:amd64                1.8.12+docs-1               amd64        Hierarchical Data Format 5 (HDF5) - runtime files - serial version
ii  libhdf5-8:amd64                1.8.13+docs-15              amd64        Hierarchical Data Format 5 (HDF5) - runtime files - serial version
rc  libhdf5-cpp-7:amd64            1.8.12+docs-1               amd64        Hierarchical Data Format 5 (HDF5) - C++ libraries
ii  libhdf5-cpp-8:amd64            1.8.13+docs-15              amd64        Hierarchical Data Format 5 (HDF5) - C++ libraries
ii  libhdf5-dev                    1.8.13+docs-15              amd64        Hierarchical Data Format 5 (HDF5) - development files - serial version
~/h2oserver$ pip freeze | grep h5py
h5py==2.3.1 (I've tried 2.5.0, and 2.3.0 as well)
h5pySWMR==0.1
~/h2oserver$ python --version
Python 3.4.2
```

Output:

```
test_parallel (h5pyswmr.test.test_parallel.TestHDF5) ...
worker 18 is reading...
worker 3 is reading...
worker 19 is writing...
worker 13 is writing...
worker 0 is reading...
worker 24 is reading...
worker 6 is reading...
worker 28 is reading...
worker 19 done writing.
worker 23 is writing...
worker 18 is done reading.
worker 4 is reading...
worker 16 is reading...
worker 22 is reading...
worker 8 is reading...
worker 14 is reading...
worker 2 is reading...
worker 12 is reading...
worker 3 is done reading.
worker 20 is reading...
worker 26 is reading...
worker 1 is reading...
worker 10 is reading...
worker 13 done writing.
worker 24 is done reading.
worker 0 is done reading.
worker 6 is done reading.
worker 4 is done reading.
worker 9 is writing...
worker 28 is done reading.
worker 15 is writing...
worker 27 is writing...
worker 25 is writing...
FAIL

======================================================================
FAIL: test_parallel (h5pyswmr.test.test_parallel.TestHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 83, in test_parallel
    self.assertTrue(np.all(dst[0:50, ] == i))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 19.331s

FAILED (failures=1)
worker 22 is done reading.
worker 26 is done reading.
worker 1 is done reading.
worker 12 is done reading.
worker 2 is done reading.
worker 20 is done reading.
worker 8 is done reading.
worker 14 is done reading.
worker 16 is done reading.
worker 10 is done reading.
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 62, in worker_write
    dst[0:50, ] = i
Process Process-16:
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/h5pyswmr.py", line 117, in func_wrapper
    with redis_lock(redis_conn, lock_w):
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 62, in worker_write
    dst[0:50, ] = i
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File /home/user/env/lib/python3.4/site-packages/h5pyswmr/h5pyswmr.py", line 117, in func_wrapper
    with redis_lock(redis_conn, lock_w):
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/locking.py", line 122, in redis_lock
    raise LockException("could not acquire lock {0}".format(lockname))
h5pyswmr.locking.LockException: could not acquire lock w__/tmp/parallel_test.h5
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/locking.py", line 122, in redis_lock
    raise LockException("could not acquire lock {0}".format(lockname))
h5pyswmr.locking.LockException: could not acquire lock w__/tmp/parallel_test.h5
Process Process-28:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 62, in worker_write
    dst[0:50, ] = i
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/h5pyswmr.py", line 117, in func_wrapper
    with redis_lock(redis_conn, lock_w):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/locking.py", line 122, in redis_lock
    raise LockException("could not acquire lock {0}".format(lockname))
h5pyswmr.locking.LockException: could not acquire lock w__/tmp/parallel_test.h5
Process Process-26:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 62, in worker_write
    dst[0:50, ] = i
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/h5pyswmr.py", line 117, in func_wrapper
    with redis_lock(redis_conn, lock_w):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/user/env/lib/python3.4/site-packages/h5pyswmr/locking.py", line 122, in redis_lock
    raise LockException("could not acquire lock {0}".format(lockname))
h5pyswmr.locking.LockException: could not acquire lock w__/tmp/parallel_test.h5
```

**Comment by bastianlb** [comment]
Sometimes I won't get the LockException:

```
worker 0 is reading...
worker 12 is reading...
worker 22 is reading...
worker 16 is reading...
worker 8 is reading...
worker 22 is done reading.
worker 4 is reading...
worker 28 is reading...
worker 18 is reading...
worker 10 is reading...
worker 14 is reading...
worker 2 is reading...
worker 1 is reading...
worker 3 is reading...
worker 28 is done reading.
worker 24 is reading...
worker 6 is reading...
worker 20 is reading...
worker 0 is done reading.
worker 16 is done reading.
worker 26 is reading...
worker 10 is done reading.
worker 2 is done reading.
worker 12 is done reading.
worker 8 is done reading.
worker 18 is done reading.
worker 20 is done reading.
worker 25 is writing...
worker 27 is writing...
worker 26 is done reading.
worker 6 is done reading.
worker 25 done writing.
worker 3 is done reading.
worker 27 done writing.
FAIL

======================================================================
FAIL: test_parallel (h5pyswmr.test.test_parallel.TestHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/usr/env/lib/python3.4/site-packages/h5pyswmr/test/test_parallel.py", line 83, in test_parallel
    self.assertTrue(np.all(dst[0:50, ] == i))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 18.369s

FAILED (failures=1)
worker 24 is done reading.
worker 5 is writing...
worker 5 done writing.
worker 14 is done reading.
worker 1 is done reading.
worker 19 is writing...
worker 19 done writing.
worker 4 is done reading.
worker 23 is writing...
worker 23 done writing.
```

Redis output:

```

3190:M 19 May 14:32:18.612 * The server is now ready to accept connections on port 6379
3190:M 19 May 14:32:19.609 - DB 0: 2 keys (0 volatile) in 4 slots HT.
3190:M 19 May 14:32:19.609 - 0 clients connected (0 slaves), 450208 bytes in use
3190:M 19 May 14:32:21.606 - Accepted ::1:58781
3190:M 19 May 14:32:24.643 - DB 0: 2 keys (0 volatile) in 4 slots HT.
3190:M 19 May 14:32:24.643 - 1 clients connected (0 slaves), 506968 bytes in use
3190:M 19 May 14:32:28.407 - Accepted ::1:58782
3190:M 19 May 14:32:28.426 - Accepted ::1:58783
3190:M 19 May 14:32:28.507 - Accepted ::1:58784
3190:M 19 May 14:32:28.547 - Accepted ::1:58785
3190:M 19 May 14:32:28.565 - Accepted ::1:58786
3190:M 19 May 14:32:28.587 - Client closed connection
3190:M 19 May 14:32:28.608 - Accepted ::1:58787
3190:M 19 May 14:32:28.669 - Accepted ::1:58788
3190:M 19 May 14:32:28.757 - Accepted ::1:58789
3190:M 19 May 14:32:28.759 - Accepted ::1:58790
3190:M 19 May 14:32:28.787 - Accepted ::1:58791
3190:M 19 May 14:32:28.810 - Accepted ::1:58792
3190:M 19 May 14:32:28.811 - Accepted ::1:58793
3190:M 19 May 14:32:29.055 - Accepted ::1:58794
3190:M 19 May 14:32:29.259 - Accepted ::1:58795
3190:M 19 May 14:32:29.262 - Client closed connection
3190:M 19 May 14:32:29.274 - Accepted ::1:58796
3190:M 19 May 14:32:29.713 - DB 0: 2 keys (0 volatile) in 8 slots HT.
3190:M 19 May 14:32:29.713 - 14 clients connected (0 slaves), 741488 bytes in use
3190:M 19 May 14:32:34.424 - Client closed connection
3190:M 19 May 14:32:34.582 - Client closed connection
3190:M 19 May 14:32:35.070 - Accepted ::1:58797
3190:M 19 May 14:32:36.109 - DB 0: 2 keys (0 volatile) in 8 slots HT.
3190:M 19 May 14:32:38.973 - 13 clients connected (0 slaves), 720616 bytes in use
3190:M 19 May 14:32:38.978 - Accepted ::1:58798
3190:M 19 May 14:32:38.978 - Accepted ::1:58799
3190:M 19 May 14:32:38.979 - Client closed connection
3190:M 19 May 14:32:39.213 - Accepted ::1:58800
3190:M 19 May 14:32:39.213 - Accepted ::1:58801
3190:M 19 May 14:32:39.256 - Client closed connection
3190:M 19 May 14:32:39.271 - Client closed connection
3190:M 19 May 14:32:39.332 - Client closed connection
3190:M 19 May 14:32:39.360 - Client closed connection
3190:M 19 May 14:32:39.380 - Client closed connection
3190:M 19 May 14:32:39.397 - Client closed connection
3190:M 19 May 14:32:39.887 - Client closed connection
3190:M 19 May 14:32:39.904 - Client closed connection
3190:M 19 May 14:32:40.012 - Client closed connection
3190:M 19 May 14:32:40.016 - Client closed connection
3190:M 19 May 14:32:40.048 - Client closed connection
3190:M 19 May 14:32:40.387 - Client closed connection
3190:M 19 May 14:32:40.732 - Accepted ::1:58802
3190:M 19 May 14:32:40.841 - Client closed connection
3190:M 19 May 14:32:41.618 - Client closed connection
3190:M 19 May 14:32:41.745 - Client closed connection
3190:M 19 May 14:32:41.758 - Accepted ::1:58803
3190:M 19 May 14:32:41.989 - Client closed connection
3190:M 19 May 14:32:42.300 - Client closed connection
3190:M 19 May 14:32:42.449 - Accepted ::1:58804
3190:M 19 May 14:32:42.523 - Client closed connection
3190:M 19 May 14:32:42.954 - Client closed connection
```

**Comment by weatherfrog** [comment]
Thanks for your interest in the package. I'll try to reproduce the error and report back.
The package is certainly not yet rock-solid. But we've been using it in production for some months now and it works well.

**Comment by bastianlb** [comment]
Ok, here is some extra info on my system in case it makes a difference, thanks for your time.

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-4-amd64
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.14.1
nose: 1.3.3
Cython: 0.22
numpy: 1.9.2
scipy: None
statsmodels: None
IPython: 2.1.0
sphinx: None
patsy: None
scikits.timeseries: None
dateutil: 2.4.1
pytz: 2015.4
bottleneck: None
tables: 3.2.0
numexpr: 2.4
matplotlib: None
openpyxl: None
xlrd: 0.9.3
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.3.2
html5lib: None
httplib2: 0.9
apiclient: None
rpy2: None
sqlalchemy: 0.9.8
pymysql: None
psycopg2: 2.6 (dt dec pq3 ext lo64)
```

**Comment by weatherfrog** [comment]
I fixed the problem. It was just the test case that was broken, not the library. Problem was that the test method did not wait for the workers to complete. Instead, it just waited for 5 seconds, which was obviously not enough on your machine. The master branch now contains a new version 0.2 that fixes some other issues as well. See CHANGES.txt. I will soon upload the library to pypi.

**Comment by bastianlb** [comment]
Ok, thanks! Also might I suggest making [this code](https://github.com/meteotest/h5pySWMR/blob/master/h5pyswmr/locking.py#L71-L75) a little more general? For instance, if you want to decorate an object with no `file` attribute, or decorate methods this fails. If you have any ideas I am happy to submit a PR. Similar for writer.

**Comment by weatherfrog** [comment]
You are right. It would be nice if `reader` and `writer` were more "polymorphic". However, we need a way of specifying the resource to be synchronized, i.e., the name of the file. For functions, the following might be appropriate?

``` python
@reader('resourcename')
def myreader():
```

But what about class methods?
